#!/usr/bin/env zsh
# Regression test for install.zsh corrupting update-workbench/update.zsh.
#
# Prior versions of install.zsh installed `update.wb` as a symlink to
# `update-workbench/update.zsh`. A later refactor switched `update.wb` to a
# deprecation shim generated by `cat > "$BIN_DIR/update.wb"`. On a host that
# still had the legacy symlink, `cat >` followed it and overwrote the real
# `update.zsh` with the shim, leaving a 3-line self-referential forwarder.
#
# Fix: `rm -f "$DEPRECATED_SHIM"` before the heredoc so any legacy symlink is
# severed before writing.

set -euo pipefail
SCRIPT_DIR="${0:A:h}"
REPO_ROOT="${SCRIPT_DIR}/.."

scratch="$(mktemp -d)"
trap "rm -rf '$scratch'" EXIT

real_update_zsh="${REPO_ROOT}/update-workbench/update.zsh"
expected_sha="$(shasum -a 256 "$real_update_zsh" | cut -d' ' -f1)"

# Fake $HOME containing the legacy symlink update.wb -> real update.zsh
fake_home="$scratch/home"
mkdir -p "$fake_home/.local/bin"
ln -sf "$real_update_zsh" "$fake_home/.local/bin/update.wb"

# Run install.zsh with HOME pointing at the fake tree
HOME="$fake_home" zsh "${REPO_ROOT}/install.zsh" >/dev/null 2>&1 || true

# Real update.zsh must be byte-identical after install
actual_sha="$(shasum -a 256 "$real_update_zsh" | cut -d' ' -f1)"
if [[ "$actual_sha" != "$expected_sha" ]]; then
  print -r -- "FAIL: install.zsh corrupted update.zsh via legacy update.wb symlink"
  print -r -- "  expected sha: $expected_sha"
  print -r -- "  actual sha:   $actual_sha"
  exit 1
fi

# update.wb in fake HOME must be a regular file (not the legacy symlink)
if [[ -L "$fake_home/.local/bin/update.wb" ]]; then
  print -r -- "FAIL: update.wb still a symlink after install"
  exit 1
fi
if [[ ! -f "$fake_home/.local/bin/update.wb" ]]; then
  print -r -- "FAIL: update.wb shim not written"
  exit 1
fi

# Shim must contain the deprecation forwarder
if ! grep -q "deprecated" "$fake_home/.local/bin/update.wb"; then
  print -r -- "FAIL: update.wb does not contain deprecation banner"
  exit 1
fi

print -r -- "PASS: install.zsh severs legacy update.wb symlink before writing the shim"
